<a href="https://colab.research.google.com/github/25wh1a05h2-source/NASSCOM/blob/main/nasscom1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
n = [1,2,97,3,4,98,76,4,69,96]
n = list(set(n))
for i in range (len(n)):
    for j in range(len(n)-i-1):
        if n[j] < n[j+1]:
            n[j],n[j+1] = n[j+1],n[j]
print("The second largest element is",n[1])

The second largest element is 97


In [ ]:
n = [1,22,3,4,5,22,5,4,4]
for i in range(len(n)):
    c = 0
    for j in range(len(n)):
        if n[i] == n[j]:
            c+=1
    print(n[i],":",c)

1 : 1
22 : 2
3 : 1
4 : 3
5 : 2
22 : 2
5 : 2
4 : 3
4 : 3


In [ ]:
def freq(n):
    v = []
    for i in range(len(n)):
        if n[i] not in v:
            c = 0
            for j in range(len(n)):
                if n[i] == n[j]:
                    c+=1
            print(n[i],":",c)
        v.append(n[i])
freq([1,3,3,4,55,55,4,2,8,9])

1 : 1
3 : 2
4 : 2
55 : 2
2 : 1
8 : 1
9 : 1


In [ ]:
n = [1,4,6,8,3,2,3,2,1,8]
n = list(set(n))
print(n)

[1, 2, 3, 4, 6, 8]


In [ ]:
n = [1,22,3,4,5,22,5,4,4]
for i in range(len(n)):
    c = 0
    for j in range(len(n)):
        if n[i] == n[j]:
            c+=1
    print(n[i],":",c)

In [ ]:
def remove(n):
    v = []
    for i in n:
        if i not in v:
            v.append(i)
    print(v)
remove([1,2,33,4,33,5,6,5,7,7])

[1, 2, 33, 4, 5, 6, 7]


In [ ]:
def rotate(n):
    v = [0]*len(n)
    b = 2
    k = len(n)
    for i in range(k):
        if i+2 >= k:
            v[i+2-k] = n[i]
        if i+2 < k:
            v[i+2] = n[i]
    print(v)
rotate([1,2,3,4,5,6,7])

[6, 7, 1, 2, 3, 4, 5]


In [ ]:
def pairs(n,k):
    v = []
    for i in range(len(n)):
        for j in range(i+1,len(n)):
            if n[i]+n[j] == k:
                print(n[i],n[j])
pairs([1,2,3,4,5,6,7,8,9,10,5],10)

1 9
2 8
3 7
4 6
5 5


In [ ]:
def lenof(n):
    n = sorted(n)
    c=1
    for j in range(len(n)-1):
        if n[j]+1 == n[j+1]:
            c+=1
    print(c)
lenof([100,2,4,1,6,3,20])

4


In [ ]:
def major(n):
    k=0
    v =[]
    for i in n:
        if n.count(i) > len(n)/2:
            if i not in v:
                print(i)
            v.append(i)
    if len(v) == 0:
        print("No majority element")
major([1,2,3,4,4,4,4,4])

4


In [ ]:
import numpy as np

A = np.array(eval(input("Enter Matrix A: ")))
B = np.array(eval(input("Enter Matrix B: ")))

print("Addition is:\n",A + B)
print("subtraction is:\n",A - B)
print("Multiplication is:\n",A @ B)

Enter Matrix A: [[1,2],[3,4]]
Enter Matrix B: [[5,6],[7,8]]
Addition is:
 [[ 6  8]
 [10 12]]
subtraction is:
 [[-4 -4]
 [-4 -4]]
Multiplication is:
 [[19 22]
 [43 50]]


In [ ]:
from datetime import datetime,date,timedelta
n = datetime.now()
print("Date and Time =",n)
t = date.today()
print("Today = ",t)
d = date(2007,6,15)
print("DOB =",d)
dby = t + timedelta(days=2)
print(dby)
f = n.strftime("Formatted date = %d-%m-%y\nFormatted time = %H:%M:%S")
print(f)

Date and Time = 2026-07-16 04:37:05.497449
Today =  2026-07-16
DOB = 2007-06-15
2026-07-18
Formatted date = 16-07-26
Formatted time = 04:37:05
